### ISSUE TITLE
MaxPool ONNX conversion error

### ISSUE THREAD

**Issue by sdemarch** [NeVerTools/pyNeVer#4]
The ONNX "MaxPool" node in the attached VNNCOMP21 network parameters are not the expected in [conversion.py](https://github.com/NeVerTools/pyNeVer/blob/main/pynever/strategies/conversion.py) at lines 741-745. Is it a problem of the network or the conversion algorithm should improve the reading?

[Convnet_maxpool.zip](https://github.com/NeVerTools/pyNeVer/files/9188026/Convnet_maxpool.zip)

**Comment by darioguidotti** [comment]
Implicit onnx attribute were unsupported, fixed.
